# Change the default embedded server port
server.port=8083

# PostgreSQL Database Configuration (values are injected by Render)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# When the application starts, automatically update the database schema (e.g., create tables)
spring.jpa.hibernate.ddl-auto=update
