# Change the default embedded server port
server.port=8083

# PostgreSQL Database Configuration (values are injected by Render)
spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:postgres}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# When the application starts, automatically update the database schema (e.g., create tables)
spring.jpa.hibernate.ddl-auto=update
