name: Build and Publish Docker Container

on: # <-- Required
  push:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    # Give GitHub Actions permission to write to the Packages registry
    permissions:
      contents: read
      packages: write

    steps: # <-- Required
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven # <-- Belongs here
        
    - name: Grant execute permission for mvnw
      run: |
        sed -i 's/\r$//' mvnw
        chmod +x mvnw
        
    - name: Build with Maven
      run: ./mvnw clean package -DskipTests
